// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Opções padrão do Firebase geradas automaticamente pelo FlutterFire CLI.
///
/// Fornece as configurações necessárias para inicializar o Firebase em cada
/// plataforma suportada (web, Android, iOS, etc.).  As plataformas não
/// configuradas lançam [UnsupportedError] se forem utilizadas.
///
/// Exemplo de uso:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  /// Devolve as [FirebaseOptions] adequadas à plataforma em execução.
  ///
  /// Suporta web e Android. Outras plataformas (iOS, macOS, Windows, Linux)
  /// lançam [UnsupportedError] porque ainda não foram configuradas.
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  /// Configuração do Firebase para a plataforma web.
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgEK3h_71DgR8OQIXc_CLXMIhc_uZJZLs',
    appId: '1:258705131162:web:e556580ada03a086078123',
    messagingSenderId: '258705131162',
    projectId: 'nutriscan-859af',
    authDomain: 'nutriscan-859af.firebaseapp.com',
    storageBucket: 'nutriscan-859af.firebasestorage.app',
  );

  /// Configuração do Firebase para a plataforma Android.
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATTGeeYrVepWzdVz2KwwLqYvfHlwJESWU',
    appId: '1:258705131162:android:08b1c7212143da09078123',
    messagingSenderId: '258705131162',
    projectId: 'nutriscan-859af',
    storageBucket: 'nutriscan-859af.firebasestorage.app',
  );
}